Improve UI of post page
WSU-4110/Degree-Door pull request #55
Opened 2022-11-02 00:29 UTC by majedau

2022-11-02 00:32 UTC, ZwarA01 approved these changes
Everything looks good, just make sure you add the nav bar :)

2022-11-02 00:32 UTC, PattyCoding123 requested changes

2022-11-02 00:32 UTC, PattyCoding123 commented on pages/post.js
> +      <div class="box-border h-max-[100vh] w-30 p-20">
Add Navbar at the top of the page

2022-11-08 17:26 UTC, PattyCoding123 approved these changes
Thank you for adding the Navbar and good job and making the links only render if provided

2022-11-08 17:26 UTC, merged